name: validate - CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main", "release/*" ]
    
  workflow_dispatch:

jobs:
  testing:
    name: Test
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.22

    - name: Run tests
      run: go test -v ./...
